name: Block Excel Changes on All Platforms

on:
  pull_request:

jobs:
  check_excel:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v3

      - name: Fetch main branch
        run: git fetch origin main

      - name: Check for Excel changes
        shell: bash
        run: |
          CHANGED=$(git diff --name-only origin/main...HEAD | grep 'ProjectManagement_Vorlage.xlsx' || true)
          if [ "$CHANGED" != "" ]; then
            echo "❌ Die Datei 'ProjectManagement_Vorlage.xlsx' darf nicht geändert werden!"
            exit 1
          else
            echo "✅ Keine Änderungen an 'ProjectManagement_Vorlage.xlsx' erkannt."
          fi
